server:
  port: 8090

spring:
  application:
    name: my-eureka-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

  instance:
    prefer-ip-address: true